import json
from datetime import datetime
from typing import Dict, Any, List
from src.reasoning.schemas import CounterfactualResponse

def get_verdict_badge_style(verdict: str) -> Dict[str, str]:
    """Returns CSS styles and icon for a given verdict."""
    v = verdict.upper()
    if "PREVENTED" in v:
        return {
            "color": "#00e676",
            "bg": "rgba(0, 230, 118, 0.12)",
            "border": "#00e676",
            "icon": "🛡️",
            "label": "EXPLOIT PREVENTED"
        }
    elif "PARTIALLY" in v:
        return {
            "color": "#ffb300",
            "bg": "rgba(255, 179, 0, 0.12)",
            "border": "#ffb300",
            "icon": "⚠️",
            "label": "PARTIALLY MITIGATED"
        }
    elif "PERSIST" in v or "EXPLOIT" in v:
        return {
            "color": "#ff5252",
            "bg": "rgba(255, 82, 82, 0.12)",
            "border": "#ff5252",
            "icon": "🚨",
            "label": "VULNERABILITY PERSISTS"
        }
    elif "SHIFT" in v:
        return {
            "color": "#e040fb",
            "bg": "rgba(224, 64, 251, 0.12)",
            "border": "#e040fb",
            "icon": "🔄",
            "label": "ATTACK VECTOR SHIFTED"
        }
    else:
        return {
            "color": "#90caf9",
            "bg": "rgba(144, 202, 249, 0.12)",
            "border": "#90caf9",
            "icon": "❓",
            "label": "INCONCLUSIVE EVIDENCE"
        }

def generate_markdown_report(
    query: str,
    protocol: str,
    response: CounterfactualResponse,
    retrieved_chunks: List[Dict[str, Any]]
) -> str:
    """Generates an audit-grade Markdown report from a counterfactual simulation."""
    timestamp = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")
    
    citations_md = "\n".join([f"- {c}" for c in response.source_citations]) or "None explicitly referenced."
    residual_md = "\n".join([f"- ⚠️ {r}" for r in response.residual_risks]) or "No immediate residual risks detected."
    causal_md = "\n".join([f"{i}. {step}" for i, step in enumerate(response.causal_reasoning_steps, 1)])

    evidence_table = "| Rank | Protocol | Section | RRF Score | Citation Source |\n| :--- | :--- | :--- | :--- | :--- |\n"
    for chunk in retrieved_chunks:
        evidence_table += f"| {chunk.get('rank', '-')} | {chunk.get('protocol', '-')} | {chunk.get('section', '-')} | {chunk.get('rrf_score', '-')} | {chunk.get('sources', '-')} |\n"

    report = f"""# CounterChain Security Audit: Counterfactual Exploit Assessment
**Generated by CounterChain (Nemotron-3.5 + BGE Hybrid RAG)**
**Timestamp**: `{timestamp}`
**Target Protocol**: `{protocol}`
**Verification Invariant**: `{query}`

---

## 1. Executive Summary
- **Verdict**: **{response.verdict.value}**
- **Confidence Level**: **{response.confidence_score * 100:.1f}%**
- **Overview**: {response.executive_summary}

---

## 2. Causal Divergence Analysis
- **Execution Divergence Point**: 
  > `{response.divergence_point}`

### Step-by-Step Causal Trace:
{causal_md}

---

## 3. Residual Risks & Security Considerations
{residual_md}

---

## 4. Recommended Smart Contract Patch
```solidity
{response.recommended_code_patch}
```

---

## 5. Retrieved Grounding Evidence
{evidence_table}

### Citations:
{citations_md}

---
*Report generated strictly from verified post-mortems (DeFiHackLabs & Rekt.news).*
"""
    return report

def export_json_report(
    query: str,
    protocol: str,
    response: CounterfactualResponse,
    retrieved_chunks: List[Dict[str, Any]]
) -> str:
    """Exports the simulation as structured JSON."""
    data = {
        "timestamp": datetime.utcnow().isoformat(),
        "protocol": protocol,
        "query": query,
        "result": response.model_dump(),
        "retrieved_evidence": retrieved_chunks
    }
    return json.dumps(data, indent=2)
